from app.extensions import db

class Cliente(db.Model):
    __tablename__ = "clientes"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    codigo_cliente = db.Column(db.String(20), unique=True, nullable=False)  # Cód.
    nombre_cliente = db.Column(db.String(255))  # Cliente
    grupo = db.Column(db.String(100))
    nombre2 = db.Column(db.String(100))
    nombre3 = db.Column(db.String(100))
    nombre4 = db.Column(db.String(100))
    sociedad = db.Column(db.String(50))
    organizacion_ventas = db.Column(db.String(50))
    canal_distribucion = db.Column(db.String(50))
    sector = db.Column(db.String(50))
    zona_ventas = db.Column(db.String(50))
    oficina_ventas = db.Column(db.String(50))
    grupo_clientes = db.Column(db.String(50))
    nombre_vendedor = db.Column(db.String(100))
    codigo_vendedor = db.Column(db.String(50))
    zona_transporte = db.Column(db.String(50))
    descripcion_zona_transp = db.Column(db.String(100))
    poblacion = db.Column(db.String(100))
    calle = db.Column(db.String(255))
    numero_identificacion = db.Column(db.String(50))
    condicion_pago = db.Column(db.String(50))
    vias_pago = db.Column(db.String(100))
    contacto_cliente = db.Column(db.String(100))
    nombre_pila_contacto = db.Column(db.String(100))
    denominacion_fiscal = db.Column(db.String(100))
    correo_contacto = db.Column(db.String(150))
    telefono_contacto = db.Column(db.String(50))
    celular_contacto = db.Column(db.String(50))
    telefono1 = db.Column(db.String(50))
    fax = db.Column(db.String(50))
    motivo_bloqueo_pedido = db.Column(db.String(255))
    clasificacion_impuesto = db.Column(db.String(50))
    concepto_busqueda = db.Column(db.String(100))
    id_responsable_cartera = db.Column(db.String(50))
    responsable_deudor = db.Column(db.String(100))
    telefono_responsable = db.Column(db.String(50))
    nota_interna = db.Column(db.Text)
    fecha_creacion = db.Column(db.Date)
    telefono3 = db.Column(db.String(50))
    correo_ejecutivo = db.Column(db.String(150))
    tipo_cliente = db.Column(db.String(50))
    kam_regional = db.Column(db.String(100))
    centro_expedicion = db.Column(db.String(50))
    aplica_ebill = db.Column(db.Boolean, default=False)
    correo1 = db.Column(db.String(150))
    correo2 = db.Column(db.String(150))
    grupo1_foco = db.Column(db.String(100))
    grupo2_comercial = db.Column(db.String(100))
    grupo3_acuerdo_pago = db.Column(db.String(100))
    grupo4_sucursal = db.Column(db.String(100))
    cuadrante_cliente = db.Column(db.String(50))
    doble_razon_social = db.Column(db.String(255))
    clasificacion_doble = db.Column(db.String(100))
    hp_sum = db.Column(db.String(50))
    hikvision = db.Column(db.String(50))
    hilook = db.Column(db.String(50))
    ezviz = db.Column(db.String(50))
    clasificacion = db.Column(db.String(100))
    kam = db.Column(db.String(100))
    director = db.Column(db.String(100))
    foco = db.Column(db.String(100))

    def __repr__(self):
        return f"<Cliente {self.codigo_cliente} - {self.nombre_cliente}>"
